---
# Deployment of our jira-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: jira-service
  replicas: 1
  template:
    metadata:
      labels:
        run: jira-service
        app.kubernetes.io/name: jira-service
        app.kubernetes.io/version: 0.8.0
    spec:
      containers:
        - name: jira-service
          image: keptnsandbox/jira-service:0.8.0
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: JIRA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-base-url
            - name: JIRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-username
            - name: JIRA_REPORTER_ID
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-reporter-user-id
            - name: JIRA_ASSIGNEE_ID
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-assignee-user-id
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-api-token
            - name: JIRA_PROJECT_KEY
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-project-key
            - name: JIRA_ISSUE_TYPE
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-issue-type
            - name: JIRA_TICKET_FOR_PROBLEMS
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-create-ticket-for-problems
            - name: JIRA_TICKET_FOR_EVALUATIONS
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: jira-create-ticket-for-evaluations
            - name: DT_TENANT
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_TENANT
                  optional: true
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_API_TOKEN
                  optional: true
            - name: KEPTN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: keptn-domain
            - name: KEPTN_BRIDGE_URL
              valueFrom:
                secretKeyRef:
                  name: jira-details
                  key: keptn-bridge-url
                  optional: true
            - name: SEND_EVENT
              value: 'true'
            - name: DEBUG
              value: 'false'
        - name: distributor
          image: keptn/distributor:0.8.4
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: VERSION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
      serviceAccountName: keptn-default
---
# Expose jira-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: jira-service
  namespace: keptn
  labels:
    run: jira-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: jira-service